config/routes.rb
Facebook::Application.routes.draw do
  mount StatBoard::Engine, :at => "/stats"

  resource :user

  match 'wall_pics' => 'photos#wall'
  match 'profile_pics' => 'photos#profile'
  match 'friend_pics' => 'photos#friends'

  match 'logout' => 'sessions#destroy'
  match '/auth/:provider/callback' => 'sessions#create'

  root :to => 'welcome#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :access_token, :name

  def self.from_access_token(token)
    fb_user = FbGraph::User.me(token).fetch
    user = find_or_create_by_name(fb_user.name)
    user.update_attribute(:access_token, fb_user.access_token)
    user
  end

  def wall_photos
    album_of_type('wall').photos
  end

  def profile_pics
    album_of_type('profile').photos
  end

  def friend_pics
    friends.flat_map do |friend|
      friend.photos_of_user
    end
  end

  private

  def friends
    fb_user.friends.select{|a| a.name.include?('Fatsi')}.map do |f|
      FbPhoto::Friend.new(f, self)
    end
  end

  def album_of_type(type)
    fb_user.albums.select{|a| a.type == type}.first
  end

  def fb_user
    @fb_user ||= FbGraph::User.me(access_token).fetch
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def wall
    @photo_type = 'wall'
    @photos = current_user.wall_photos
    render :partial => 'show_photos'
  end

  def profile
    @photo_type = 'profile pictures'
    @photos = current_user.profile_pics
    render :partial => 'show_photos'
  end

  def friends
    @photo_type = "friend's pictures (Fatsi's only at the moment)"
    @photos = current_user.friend_pics
    render :partial => 'show_photos'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_access_token(request.env['omniauth.auth'].credentials.token)
    session[:user_id] = user.id

    redirect_to user_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to user_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_show_photos.html.erb
Showing photos from your <%= @photo_type %>!

<ul>
	<% @photos.each do |photo| %>
		<%= image_tag photo.source %>
	<% end %>
</ul>

app/views/users/show.html.erb
<%#= image_tag @photo.source %>
<%= link_to 'Sign Out', logout_url %>
<%= link_to 'Wall Photos', wall_pics_url %>
<%= link_to 'Profile Pics', profile_pics_url %>
<%= link_to 'Friend Pics', friend_pics_url %>

app/views/welcome/home.html.erb
<%= link_to "Sign in with Facebook", "/auth/facebook" %>